---
title: "Americans in the Heartland not in Love with Weather There"
author: "Joe Rubash"
date: "September 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# 01 - Libraries----------------------------------------------------------------

library(tidyverse)
library(httr)
library(readxl)
library(wesanderson)
library(scales)
library(ggthemes)



# 02 - Load and save data-------------------------------------------------------
# data URL
file.url <- "https://query.data.world/s/jojvebvgq7wlx7ircyeqad6pgp3cry"

# function to read in data from net
load_data_from_net <- function(file.url){
    GET(file.url,
        write_disk(tf <- tempfile(fileext = ".xlsx")))
    read_xlsx(tf, skip = 1)
}

# once read from net save to csv in data folder
csv.file <- "./data/USA-fav-seasons.csv"

data <- if(file.exists(csv.file)) {
         read_csv(csv.file)
    } else{
        load_data_from_net(file.url) %>% 
        write_csv(., "./data/USA-fav-seasons.csv")
    }



# 03 - Format data--------------------------------------------------------------
names(data) <- make.names(names(data)) %>% 
    tolower()

# change age.group and season to factors
data <- modify_at(data,
                  .at = c("age.group",
                          "season"),
                  as.factor)

# reorder season levels 
data$season <- fct_relevel(data$season,
                           "Spring",
                           "Summer",
                           "Fall",
                           "Winter")

```

```{r Bar chart pref for seasons by age.group - ordered}
# add variable to order seasons
data.ordered <- data %>% 
    group_by(age.group) %>% 
    arrange(by = desc(preference.value),
            .by_group = TRUE) %>% 
    ungroup() %>% 
    mutate(order = row_number())


ggplot(data = data.ordered,
       aes(x = order,
           y = preference.value))+
    geom_bar(stat = "identity",
             position = "dodge",
             fill = "gray")+
    geom_bar(data = data.ordered %>%
                 group_by(age.group) %>%
                 top_n(x = .,
                       n = 1,
                       wt = preference.value) %>%
                 ungroup(),
             aes(x = order,
                 y = preference.value,
                 fill = season),
             stat = "identity",
             inheret = FALSE ,
             width = 0.9)+
    facet_grid(. ~ age.group, scales = "free")+
    labs(x = "",
         y = "% Prefered",
         fill = "Seasons",
         title = "Favorite Season Depends upon Your Age",
         subtitle = "A recent survey of Americans showed that the most preferred season appeared 
to depend upon the age of those polled. However, in all age groups winter was the
least preferred season.",
caption = "Source = https://today.yougov.com/topics/lifestyle/articles-reports/2013/06/10/fall-favorite-season-most-americans-33-heartland-l")+
    geom_text(data = data.ordered %>%
                  group_by(age.group) %>%
                  top_n(x = .,
                        n = 1,
                        wt = preference.value) %>%
                  ungroup(),
              aes(label = season,
                  y = preference.value + 0.01),
              vjust = 0)+
    theme_tufte()+
    theme(text = element_text(size = 14),
          strip.text.x = element_text(size = 14),
          plot.title = element_text(size = 24),
          plot.caption = element_text(size = 8))+
    scale_fill_manual(values = c("#99FF33", "#FFCC33", "#CC6633", "#3399FF"))+
    scale_x_continuous(breaks = data.ordered$order,
                       labels = data.ordered$season)+
    scale_y_continuous(labels = percent_format(1),
                       limits = c(0, 0.45))+
    guides(fill = "none")


ggsave("./output/season.pref.by.age.ordered.png")
```
Alternate plots... exploring other ideas
```{r Bar chart pref for seasons by age.group}
# add variable to order seasons
data.ordered <- data %>% 
    group_by(age.group) %>% 
    arrange(by = preference.value,
            .by_group = TRUE) %>% 
    mutate(season.index = 1:length(season),
           alpha = if_else(season.index %in% c(1, 2, 3), "not fav season", "favorite season"))

data.ordered$alpha <- fct_relevel(data.ordered$alpha, "not fav season", "favorite season")

ggplot(data = data.ordered,
       aes(x = season,
                 y = preference.value))+
    geom_bar(stat = "identity",
             position = "dodge",
             fill = "gray")+
    geom_bar(data = data %>% 
                 group_by(age.group) %>% 
                 top_n(x = ., 
                       n = 1,
                       wt = preference.value) %>% 
                 ungroup(),
             aes(fill = season),
             stat = "identity")+
    facet_grid(. ~ age.group, scales = "free")+
    scale_y_continuous(labels = percent_format(1))+
    labs(x = "",
         y = "% Prefered",
         fill = "Seasons",
         title = "Favorite Season of Depends on your Age",
         caption = "data from the ....")+
    theme_tufte()+
    theme(strip.text.y = element_text(angle = 0),
          legend.position = "bottom",
          text = element_text(size = 14))+
    scale_fill_manual(values = c("#99FF33", "#FFCC33", "#CC6633", "#3399FF"))+
    geom_text(data = data %>% 
                 group_by(age.group) %>% 
                 top_n(x = ., 
                       n = 1,
                       wt = preference.value) %>% 
                 ungroup(),
              aes(label = season,
                  y = preference.value + 0.01),
              vjust = 0)
              

ggsave("./output/season.pref.by.age.png")
```
```{r age group plot}

age.group.df <- data.frame(age = c(0:100))
age.group.df$age.group <-  if_else(age.group.df$age > 17 & age.group.df$age < 35,
                           "18-34 years old",
                           if_else(age.group.df$age >34 & age.group.df$age < 55,
                                   "35-54 years old",
                                   if_else(age.group.df$age > 54, "55 and over", "NA")))

ggplot(data = age.group.df,
       aes(x = age,
           fill = age.group),
       y = 1)+
    geom_bar()
```

